version: '3.3'

services:
  keycloak:
    container_name: sko-keycloak
    build:
      context: ./keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://sko-batch-postgres:5432/sko_auth
      - KC_DB_USERNAME=sko_keycloak
      - KC_DB_PASSWORD=keycloak2
    ports:
      - "8443:8443"
    depends_on:
      - sko-batch-postgres
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    command:
      - start '--optimized' --import-realm

  sko-batch-postgres:
    image: postgres:15-alpine
    container_name: sko-batch-postgres
    restart: always
    environment:
      - POSTGRES_USER=sko
      - POSTGRES_PASSWORD=sko-password
      - POSTGRES_DB=sko-db
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - sko-batch-data:/var/lib/postgresql/data

volumes:
  sko-batch-data:
    driver: local