version: '3.3'

services:
  keycloak:
    container_name: sko-keycloak
    build:
      context: ./keycloak
    env_file:
      - .env
    ports:
      - "8443:8443"
    depends_on:
      - sko-postgres
    command:
      - start '--optimized' --import-realm --http-enabled true --http-port 8100

  sko-postgres:
    image: postgres:15-alpine
    container_name: sko-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - sko-data:/var/lib/postgresql/data

volumes:
  sko-data:
    driver: local