POST https://localhost:8443/realms/sko-realm/protocol/openid-connect/token

###
POST https://localhost:9090/api/users
Content-Type: application/json

{
  "username": "pazzio3",
  "password": "test",
  "email": "csprogrammers3@outlook.com",
  "profilePictureUrl": "test/location.jpg"
}