POST https://localhost:8443/realms/sko-realm/protocol/openid-connect/token?
Content-Type: application/x-www-form-urlencoded



###
POST https://localhost:9090/api/users
Content-Type: application/json

{
  "username": "csprogrammers@outlook.com",
  "password": "test",
  "email": "csprogrammers4@outlook.com",
  "profilePictureUrl": "test/location.jpg"
}

###
# curl 'https://localhost:8443/realms/sko-realm/protocol/openid-connect/token'
#  -H 'authority: localhost:8443'
#  -H 'accept: */*'
#  -H 'accept-language: en-US,en;q=0.9'
#  -H 'content-type: application/x-www-form-urlencoded'
#  -H 'origin: http://localhost:3000'
#  -H 'referer: http://localhost:3000/'
#  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'sec-fetch-dest: empty'
#  -H 'sec-fetch-mode: cors'
#  -H 'sec-fetch-site: cross-site'
#  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
#  --data-raw 'username=csprogrammers%40outlook.com&password=test&clientId=sko-client&clientSecret=Yn8JZT31j4cxQBRJQWUpP0hLMAI1shX7&grantType=password'
#  --compressed
POST https://localhost:8443/realms/sko-realm/protocol/openid-connect/token
authority: localhost:8443
accept: */*
accept-language: en-US,en;q=0.9
origin: http://localhost:3000
referer: http://localhost:3000/
sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded

username=csprogrammers%40outlook.com&password=test&client_id=sko-client&client_secret=Yn8JZT31j4cxQBRJQWUpP0hLMAI1shX7&grant_type=password

###

